set(headers ${headers}
	src/Common.h
	src/ConditionParser.h
	src/ConfigData.h
	src/Debug.h
	src/Hooks.h
	src/Hooks/Attach.h
	src/Hooks/Detach.h
	src/Hooks/Misc.h
	src/Hooks/Update.h
	src/LightControllers.h
	src/LightData.h
	src/Manager.h
	src/PCH.h
	src/Papyrus.h
	src/ProcessedLights.h
	src/RE.h
	src/Settings.h
	src/SourceData.h
)
