set(sources ${sources}
	src/ConditionParser.cpp
	src/ConfigData.cpp
	src/Debug.cpp
	src/Hooks.cpp
	src/Hooks/Attach.cpp
	src/Hooks/Detach.cpp
	src/Hooks/Misc.cpp
	src/Hooks/Update.cpp
	src/LightControllers.cpp
	src/LightData.cpp
	src/Manager.cpp
	src/PCH.cpp
	src/Papyrus.cpp
	src/ProcessedLights.cpp
	src/RE.cpp
	src/Settings.cpp
	src/SourceData.cpp
	src/main.cpp
)
